-- 001_initial.sql
-- Initial database schema for SIEM platform

PRAGMA journal_mode=WAL;
PRAGMA synchronous=NORMAL;
PRAGMA foreign_keys=ON;

-- events: core event store with full-text search support
CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    received_at DATETIME NOT NULL DEFAULT (datetime('now')),
    source TEXT NOT NULL,
    source_type TEXT NOT NULL DEFAULT 'syslog',
    host TEXT,
    ip TEXT,
    service TEXT,
    application TEXT,
    severity TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    event_type TEXT,
    category TEXT,
    action TEXT,
    outcome TEXT,
    user TEXT,
    user_id TEXT,
    process TEXT,
    process_id TEXT,
    parent_pid TEXT,
    file_path TEXT,
    destination_ip TEXT,
    destination_port INTEGER DEFAULT 0,
    source_ip TEXT,
    source_port INTEGER DEFAULT 0,
    raw TEXT,
    raw_format TEXT,
    trace_id TEXT,
    span_id TEXT,
    attributes TEXT
);

CREATE VIRTUAL TABLE IF NOT EXISTS events_fts USING fts5(
    message,
    attributes,
    content='events',
    content_rowid='rowid'
);

-- Triggers to keep FTS index in sync with events table
CREATE TRIGGER IF NOT EXISTS events_ai AFTER INSERT ON events BEGIN
    INSERT INTO events_fts(rowid, message, attributes)
    VALUES (NEW.rowid, NEW.message, NEW.attributes);
END;

CREATE TRIGGER IF NOT EXISTS events_ad AFTER DELETE ON events BEGIN
    INSERT INTO events_fts(events_fts, rowid, message, attributes)
    VALUES ('delete', OLD.rowid, OLD.message, OLD.attributes);
END;

CREATE TRIGGER IF NOT EXISTS events_au AFTER UPDATE ON events BEGIN
    INSERT INTO events_fts(events_fts, rowid, message, attributes)
    VALUES ('delete', OLD.rowid, OLD.message, OLD.attributes);
    INSERT INTO events_fts(rowid, message, attributes)
    VALUES (NEW.rowid, NEW.message, NEW.attributes);
END;

CREATE INDEX IF NOT EXISTS idx_events_timestamp ON events(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_source ON events(source);
CREATE INDEX IF NOT EXISTS idx_events_source_type ON events(source_type);
CREATE INDEX IF NOT EXISTS idx_events_host ON events(host);
CREATE INDEX IF NOT EXISTS idx_events_service ON events(service);
CREATE INDEX IF NOT EXISTS idx_events_severity ON events(severity);
CREATE INDEX IF NOT EXISTS idx_events_event_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_category ON events(category);
CREATE INDEX IF NOT EXISTS idx_events_source_ip ON events(source_ip);
CREATE INDEX IF NOT EXISTS idx_events_destination_ip ON events(destination_ip);
CREATE INDEX IF NOT EXISTS idx_events_user ON events(user);
CREATE INDEX IF NOT EXISTS idx_events_event_id ON events(event_id);

-- ingestion_sources: manages sources configured in the system
CREATE TABLE IF NOT EXISTS ingestion_sources (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'syslog',
    config TEXT,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now')),
    enabled INTEGER NOT NULL DEFAULT 1,
    offset_file TEXT,
    last_offset TEXT
);

-- alerts: generated by detection engine
CREATE TABLE IF NOT EXISTS alerts (
    id TEXT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    detection_id TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    title TEXT NOT NULL,
    description TEXT,
    risk_score REAL,
    entities TEXT,
    events TEXT,
    metadata TEXT,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_detection_id ON alerts(detection_id);
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp);

-- incidents: security incident lifecycle
CREATE TABLE IF NOT EXISTS incidents (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now')),
    assignee TEXT,
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_severity ON incidents(severity);

-- incident_alerts: links alerts to incidents (many-to-many)
CREATE TABLE IF NOT EXISTS incident_alerts (
    incident_id TEXT NOT NULL,
    alert_id TEXT NOT NULL,
    PRIMARY KEY (incident_id, alert_id),
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE,
    FOREIGN KEY (alert_id) REFERENCES alerts(id) ON DELETE CASCADE
);

-- incident_events: links events to incidents
CREATE TABLE IF NOT EXISTS incident_events (
    incident_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    PRIMARY KEY (incident_id, event_id),
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

-- incident_entities: links entities to incidents
CREATE TABLE IF NOT EXISTS incident_entities (
    incident_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_value TEXT NOT NULL,
    PRIMARY KEY (incident_id, entity_type, entity_value),
    FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE CASCADE
);

-- detection_rules: rules that generate alerts
CREATE TABLE IF NOT EXISTS detection_rules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    query TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'medium',
    threshold_count INTEGER NOT NULL DEFAULT 1,
    threshold_window INTEGER NOT NULL DEFAULT 300,
    group_by TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_detection_rules_enabled ON detection_rules(enabled);

-- entities: deduplicated entity store
CREATE TABLE IF NOT EXISTS entities (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_value TEXT NOT NULL,
    first_seen DATETIME NOT NULL DEFAULT (datetime('now')),
    last_seen DATETIME NOT NULL DEFAULT (datetime('now')),
    count INTEGER NOT NULL DEFAULT 1,
    UNIQUE(entity_type, entity_value)
);

CREATE INDEX IF NOT EXISTS idx_entities_type ON entities(entity_type);
CREATE INDEX IF NOT EXISTS idx_entities_value ON entities(entity_value);

-- users: local authentication store
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now')),
    last_login_at DATETIME,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until DATETIME
);

-- audit_log: audit trail for all actions
CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    timestamp DATETIME NOT NULL DEFAULT (datetime('now')),
    user TEXT,
    action TEXT NOT NULL,
    resource TEXT NOT NULL,
    details TEXT,
    ip_address TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log(user);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);

-- saved_searches: persisted queries
CREATE TABLE IF NOT EXISTS saved_searches (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    query TEXT NOT NULL,
    description TEXT,
    created_by TEXT,
    created_at DATETIME NOT NULL DEFAULT (datetime('now')),
    updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_saved_searches_name ON saved_searches(name);

-- ingestion_offsets: tracks file ingestion positions
CREATE TABLE IF NOT EXISTS ingestion_offsets (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    file_path TEXT NOT NULL,
    offset INTEGER NOT NULL DEFAULT 0,
    inode INTEGER,
    timestamp DATETIME NOT NULL DEFAULT (datetime('now')),
    UNIQUE(source_id, file_path)
);

CREATE INDEX IF NOT EXISTS idx_ingestion_offsets_source_id ON ingestion_offsets(source_id);
CREATE INDEX IF NOT EXISTS idx_ingestion_offsets_file_path ON ingestion_offsets(file_path);
