package alerts

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/google/uuid"

	"quetzalog/pkg/event"
)

// Alert represents a security alert generated by a detection rule.
type Alert struct {
	ID          string    `json:"id"`
	Timestamp   time.Time `json:"timestamp"`
	DetectionID string    `json:"detection_id"`
	Severity    string    `json:"severity"`
	Status      string    `json:"status"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	RiskScore   float64   `json:"risk_score"`
	Entities    string    `json:"entities"` // JSON array
	Events      string    `json:"events"`   // JSON array
	Metadata    string    `json:"metadata"` // JSON object
	Notes       []Note    `json:"notes"`
}

// Note represents a note attached to an alert.
type Note struct {
	ID        string    `json:"id"`
	AlertID   string    `json:"alert_id"`
	CreatedAt time.Time `json:"created_at"`
	Content   string    `json:"content"`
	Author    string    `json:"author"`
}

// Store persists and queries alerts.
type Store struct {
	db            *sql.DB
	webhookNotifs []*WebhookNotifier
}

// Filter holds parameters for listing alerts.
type Filter struct {
	Severity string
	Status   string
	Limit    int
	Offset   int
}

// NewStore creates a new alert store backed by the given database.
func NewStore(db *sql.DB) *Store {
	return &Store{db: db}
}

// Create inserts a new alert and returns its ID.
func (s *Store) Create(ctx context.Context, alert *Alert) error {
	if alert == nil {
		return fmt.Errorf("nil alert provided")
	}

	if alert.ID == "" {
		alert.ID = uuid.New().String()
	}
	if alert.Status == "" {
		alert.Status = "new"
	}
	if alert.Severity == "" {
		alert.Severity = "medium"
	}
	if alert.Entities == "" {
		alert.Entities = "[]"
	}
	if alert.Events == "" {
		alert.Events = "[]"
	}
	if alert.Metadata == "" {
		alert.Metadata = "{}"
	}
	alert.Timestamp = time.Now()

	query := `INSERT INTO alerts (id, timestamp, detection_id, severity, status, title, description, risk_score, entities, events, metadata)
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`

	_, err := s.db.ExecContext(ctx, query,
		alert.ID,
		alert.Timestamp,
		alert.DetectionID,
		alert.Severity,
		alert.Status,
		alert.Title,
		alert.Description,
		alert.RiskScore,
		alert.Entities,
		alert.Events,
		alert.Metadata,
	)
	if err != nil {
		return fmt.Errorf("create alert: %w", err)
	}

	s.notifyWebhooks(ctx, alert, "alert.created")

	return nil
}

// GetByID retrieves an alert by its ID.
func (s *Store) GetByID(ctx context.Context, id string) (*Alert, error) {
	if id == "" {
		return nil, fmt.Errorf("empty alert ID")
	}

	query := `SELECT id, timestamp, detection_id, severity, status, title, description, risk_score, entities, events, metadata
	          FROM alerts WHERE id = ?`

	alert := &Alert{}
	var desc sql.NullString
	var risk sql.NullFloat64
	var entities, eventsJSON, metadata sql.NullString
	err := s.db.QueryRowContext(ctx, query, id).Scan(
		&alert.ID,
		&alert.Timestamp,
		&alert.DetectionID,
		&alert.Severity,
		&alert.Status,
		&alert.Title,
		&desc,
		&risk,
		&entities,
		&eventsJSON,
		&metadata,
	)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("alert %s not found", id)
		}
		return nil, fmt.Errorf("query alert %s: %w", id, err)
	}
	applyAlertNulls(alert, desc, risk, entities, eventsJSON, metadata)

	notes, err := s.GetNotes(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get notes for alert %s: %w", id, err)
	}
	alert.Notes = notes

	return alert, nil
}

// List returns alerts matching the given filter.
func (s *Store) List(ctx context.Context, filter Filter) ([]*Alert, error) {
	if filter.Limit <= 0 {
		filter.Limit = 100
	}
	if filter.Offset < 0 {
		filter.Offset = 0
	}

	query := `SELECT id, timestamp, detection_id, severity, status, title, description, risk_score, entities, events, metadata
	          FROM alerts WHERE 1=1`
	var args []any

	if filter.Severity != "" {
		query += " AND severity = ?"
		args = append(args, filter.Severity)
	}
	if filter.Status != "" {
		query += " AND status = ?"
		args = append(args, filter.Status)
	}
	query += " ORDER BY timestamp DESC"
	query += fmt.Sprintf(" LIMIT %d OFFSET %d", filter.Limit, filter.Offset)

	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("list alerts: %w", err)
	}
	defer rows.Close()

	var alerts []*Alert
	for rows.Next() {
		a := &Alert{}
		var desc sql.NullString
		var risk sql.NullFloat64
		var entities, eventsJSON, metadata sql.NullString
		err := rows.Scan(
			&a.ID,
			&a.Timestamp,
			&a.DetectionID,
			&a.Severity,
			&a.Status,
			&a.Title,
			&desc,
			&risk,
			&entities,
			&eventsJSON,
			&metadata,
		)
		if err != nil {
			return nil, fmt.Errorf("scan alert row: %w", err)
		}
		applyAlertNulls(a, desc, risk, entities, eventsJSON, metadata)
		alerts = append(alerts, a)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate alerts: %w", err)
	}
	rows.Close()

	ids := make([]string, 0, len(alerts))
	for _, a := range alerts {
		ids = append(ids, a.ID)
	}
	notesByAlert, err := s.notesByAlertIDs(ctx, ids)
	if err != nil {
		return nil, fmt.Errorf("get notes for alerts: %w", err)
	}
	for _, a := range alerts {
		a.Notes = notesByAlert[a.ID]
	}

	return alerts, nil
}

// UpdateStatus changes the status of an alert.
func (s *Store) UpdateStatus(ctx context.Context, id, status string) error {
	if id == "" {
		return fmt.Errorf("empty alert ID")
	}
	if status == "" {
		return fmt.Errorf("empty status")
	}

	query := `UPDATE alerts SET status = ? WHERE id = ?`
	_, err := s.db.ExecContext(ctx, query, status, id)
	if err != nil {
		return fmt.Errorf("update alert status: %w", err)
	}

	alert := &Alert{ID: id, Status: status}
	eventType := "alert.updated"
	if status == "resolved" {
		eventType = "alert.resolved"
	}
	s.notifyWebhooks(ctx, alert, eventType)

	return nil
}

// AddNote appends a note to an alert.
func (s *Store) AddNote(ctx context.Context, note *Note) error {
	if note == nil {
		return fmt.Errorf("nil note provided")
	}
	if note.AlertID == "" {
		return fmt.Errorf("empty alert ID for note")
	}
	if note.ID == "" {
		note.ID = uuid.New().String()
	}
	note.CreatedAt = time.Now()

	query := `INSERT INTO notes (id, alert_id, created_at, content, author) VALUES (?, ?, ?, ?, ?)`
	_, err := s.db.ExecContext(ctx, query,
		note.ID,
		note.AlertID,
		note.CreatedAt,
		note.Content,
		note.Author,
	)
	if err != nil {
		return fmt.Errorf("add note: %w", err)
	}

	return nil
}

func applyAlertNulls(a *Alert, description sql.NullString, risk sql.NullFloat64, entities, eventsJSON, metadata sql.NullString) {
	a.Description = description.String
	a.RiskScore = risk.Float64
	a.Entities = entities.String
	a.Events = eventsJSON.String
	a.Metadata = metadata.String
	if a.Entities == "" {
		a.Entities = "[]"
	}
	if a.Events == "" {
		a.Events = "[]"
	}
	if a.Metadata == "" {
		a.Metadata = "{}"
	}
}

// GetNotes returns all notes for a given alert.
func (s *Store) GetNotes(ctx context.Context, alertID string) ([]Note, error) {
	if alertID == "" {
		return nil, fmt.Errorf("empty alert ID")
	}

	query := `SELECT id, alert_id, created_at, content, author FROM notes WHERE alert_id = ? ORDER BY created_at ASC`
	rows, err := s.db.QueryContext(ctx, query, alertID)
	if err != nil {
		return nil, fmt.Errorf("query notes: %w", err)
	}
	defer rows.Close()

	var notes []Note
	for rows.Next() {
		var n Note
		err := rows.Scan(&n.ID, &n.AlertID, &n.CreatedAt, &n.Content, &n.Author)
		if err != nil {
			return nil, fmt.Errorf("scan note row: %w", err)
		}
		notes = append(notes, n)
	}

	return notes, nil
}

// notesPerQuery bounds how many alert ids go into a single IN (...) list so a
// large page cannot exceed the host SQLite build's variable limit.
const notesPerQuery = 500

// notesByAlertIDs loads the notes for many alerts in one query per chunk and
// groups them by alert id. Alerts without notes are absent from the map, which
// mirrors GetNotes returning a nil slice.
func (s *Store) notesByAlertIDs(ctx context.Context, ids []string) (map[string][]Note, error) {
	if len(ids) == 0 {
		return nil, nil
	}

	notes := make(map[string][]Note, len(ids))

	for start := 0; start < len(ids); start += notesPerQuery {
		end := start + notesPerQuery
		if end > len(ids) {
			end = len(ids)
		}
		chunk := ids[start:end]

		placeholders := strings.Repeat("?, ", len(chunk))
		placeholders = placeholders[:len(placeholders)-2]

		args := make([]any, 0, len(chunk))
		for _, id := range chunk {
			args = append(args, id)
		}

		query := `SELECT id, alert_id, created_at, content, author FROM notes WHERE alert_id IN (` + placeholders + `) ORDER BY alert_id, created_at ASC`
		rows, err := s.db.QueryContext(ctx, query, args...)
		if err != nil {
			return nil, fmt.Errorf("query notes: %w", err)
		}

		for rows.Next() {
			var n Note
			if err := rows.Scan(&n.ID, &n.AlertID, &n.CreatedAt, &n.Content, &n.Author); err != nil {
				rows.Close()
				return nil, fmt.Errorf("scan note row: %w", err)
			}
			notes[n.AlertID] = append(notes[n.AlertID], n)
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return nil, fmt.Errorf("iterate notes: %w", err)
		}
		rows.Close()
	}

	return notes, nil
}

// SetWebhookNotifiers registers webhook notifiers for alert events.
func (s *Store) SetWebhookNotifiers(notifiers []*WebhookNotifier) {
	s.webhookNotifs = notifiers
}

// notifyWebhooks sends webhook notifications for alert events.
func (s *Store) notifyWebhooks(ctx context.Context, alert *Alert, event string) {
	if len(s.webhookNotifs) == 0 {
		return
	}
	for _, notif := range s.webhookNotifs {
		if err := notif.Notify(ctx, alert, event); err != nil {
			slog.Warn("webhook notification failed", "error", err, "alert", alert.ID, "event", event)
		}
	}
}

// NewAlert creates a new alert with a generated ID.
func NewAlert() *Alert {
	return &Alert{
		ID:        uuid.New().String(),
		Timestamp: time.Now(),
		Status:    "new",
	}
}

// EntitiesFromEvent converts an event.Event into a JSON entities string.
func EntitiesFromEvent(ev *event.Event) string {
	if ev == nil {
		return "[]"
	}
	entity := map[string]any{
		"id":       ev.ID,
		"host":     ev.Host,
		"ip":       ev.IP,
		"source":   ev.Source,
		"user":     ev.User,
		"severity": ev.Severity,
	}
	data, _ := json.Marshal([]any{entity})
	return string(data)
}
